In [1]:
import pickle 
import pandas as pd
df=pd.read_csv('TrainDataset.csv')
df

v1                                                 v2
0     spam  U were outbid by simonwatson5120 on the Shinco...
1      ham                     Do you still have the grinder?
2      ham                     No. Yes please. Been swimming?
3      ham    No de.am seeing in online shop so that i asked.
4      ham  Faith makes things possible,Hope makes things ...
...    ...                                                ...
4452   ham               Good. Good job. I like entrepreneurs
4453   ham  Living is very simple.. Loving is also simple....
4454   ham  Msgs r not time pass.They silently say that I ...
4455   ham     What is this 'hex' place you talk of? Explain!
4456   ham                             Sorry, I'll call later

[4457 rows x 2 columns]

In [2]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
df.head()

v1                                                 v2
0  spam  U were outbid by simonwatson5120 on the Shinco...
1   ham                     Do you still have the grinder?
2   ham                     No. Yes please. Been swimming?
3   ham    No de.am seeing in online shop so that i asked.
4   ham  Faith makes things possible,Hope makes things ...

In [4]:
len(df)

4457

In [5]:
len(df.loc[df.v1=='ham'])/len(df)

0.8678483284720664

In [6]:
df.loc[df["v1"]=="spam",'v1']=1
df.loc[df["v1"]=="ham",'v1']=0
df.head()

v1                                                 v2
0  1  U were outbid by simonwatson5120 on the Shinco...
1  0                     Do you still have the grinder?
2  0                     No. Yes please. Been swimming?
3  0    No de.am seeing in online shop so that i asked.
4  0  Faith makes things possible,Hope makes things ...

In [7]:
df_x=df["v2"] 
df_y=df["v1"]

In [8]:
#tfidf_vector_first=TfidfVectorizer(min_df=1,stop_words="english")

In [9]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [10]:
cv = TfidfVectorizer(min_df=1,stop_words='english')

In [11]:
x_traincv = cv.fit_transform(["Hi How are you How are you doing","Hi what's up","Wow that's awesome,i am fine"])

In [12]:
x_traincv.toarray()

array([[0.        , 0.79596054, 0.        , 0.60534851, 0.        ],
       [0.        , 0.        , 0.        , 1.        , 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027]])

In [13]:
cv.get_feature_names()

c:\Users\parth\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['awesome', 'doing', 'fine', 'hi', 'wow']

In [14]:
tfidf_vector_second= TfidfVectorizer(min_df=1,stop_words='english')

In [15]:
x_traincv=tfidf_vector_second.fit_transform(x_train)
a=x_traincv.toarray()
#tfidf_vector_second.inverse_transform(a[0])

In [16]:
mnb = MultinomialNB()
y_train=y_train.astype('int')
y_train

3658    0
2462    1
4192    0
2097    0
2410    1
       ..
3671    0
709     0
2487    0
174     0
1146    0
Name: v1, Length: 3565, dtype: int32

In [17]:
mnb.fit(x_traincv,y_train)
testmessage=x_test.iloc[0]
testmessage

'Please protect yourself from e-threats. SIB never asks for sensitive information like Passwords,ATM/SMS PIN thru email. Never share your password with anybody.'

In [18]:
x_testcv=tfidf_vector_second.transform(x_test)

In [19]:
predictions=mnb.predict(x_testcv)
predictions

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [20]:
a=np.array(y_test)
a

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [21]:
count=0
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1
    else :
      print(i)


23
81
123
154
170
226
228
316
349
395
396
403
417
486
489
503
538
546
551
565
589
591
592
593
621
643
708
744
751
796
824
869


In [22]:
print(count)
count/len(predictions)

860


0.9641255605381166

In [23]:
def prediction_show(x):
    if x[0] == 1:
        print("This message is spam message!!")
    else:
        print("This is a ham message.")

In [24]:
message = "Congratulations! You have won a luxury vacation package for two to an exotic island! Claim your prize now by clicking the link below and entering your personal information. Hurry, this offer won't last long!"
tfidf = tfidf_vector_second
vectorize_message = tfidf.transform([message])
x=vectorize_message.toarray()
prediction = mnb.predict(x)
prediction_show(prediction)

This message is spam message!!


In [25]:
message = "Hi [Name],I hope this message finds you well. I wanted to reach out and see how you've been doing lately. It's been a while since we last caught up, and I've been thinking about you. Let\'s plan a coffee or lunch meet-up soon to reconnect and share some stories. Looking forward to hearing from you!"
tfidf = tfidf_vector_second
vectorize_message = tfidf.transform([message])
x=vectorize_message.toarray()
prediction = mnb.predict(x)
prediction_show(prediction)

This is a ham message.


In [26]:
#pickle.dump(mnb,open('model.pkl','wb'))

In [27]:
#import joblib
#joblib.dump(tfidf_vector_second, 'vectorizer.pkl')